export const ArtStyles = [
    { name: "Lascaux", year: "17k - 15k BC", prompt: "minimal angular abstract shapes with very little detail, Lascaux cave painting" },
    { name: "Egyptian", year: "3k - 30 BC", prompt: "minimal, abstract, simple flat two-dimensional Egyptian hieroglyph symbol on stone wall" },
    { name: "Antiquity", year: "800 BC - 500 AD", prompt: "classical antiquity statue" },
    { name: "Medieval", year: "500 - 1400 AD", prompt: "Christ Pantocrator (Sinai) (500 – 600)" },
    { name: "Renaissance", year: "1400 - 1600", prompt: "The Last Supper, Sistine Chapel, Birth of Venus, Mona Lisa" },
    { name: "Baroque", year: "1600 - 1750", prompt: "Las Meninas, The Night Watch, The Calling of Saint Matthew (Caravaggio), The Conversion of Saint Paul" },
    { name: "Rococo", year: "1730 - 1770", prompt: "\"The Swing\" - Jean-Honoré Fragonard, \"Pilgrimage to Cythera\" - Antoine Watteau, \"The Embarkation for Cythera\" - Jean-Antoine Watteau" },
    { name: "Neoclassicism", year: "1760 - 1840", prompt: "\"The Oath of the Horatii\" - Jacques-Louis David, \"Napoleon Crossing the Alps\" - Jacques-Louis David" },
    { name: "Romanticism", year: "1800 - 1850", prompt: "\"Wanderer above the Sea of Fog\" - Caspar David Friedrich, \"The Slave Ship\" - J.M.W. Turner, \"The Third of May 1808\" - Francisco Goya" },
    { name: "Impressionism", year: "1860 - 1890", prompt: "Monet flower fillies, Vincent van Gogh painting" },
    { name: "Cubism", year: "1907 - 1920s", prompt: "abstract angular Cubist Picasso painting" },
    { name: "Surrealism", year: "1920s - 1950s", prompt: "Salvador Dali surrealist desert painting" },
    { name: "Abstract Expressionism", year: "1940s - 1960s", prompt: "abstract Pollock action painting" },
    { name: "Postmodernism", year: "1960s - Present", prompt: "simple squares, block colors, Rothko, Mondrian" },
    { name: "Pop Art", year: "1950s - 1970s", prompt: "Andy Warhol multiple color, Lichtenstein comic" },
    { name: "Neoexpressionist", year: "1980s - 2000s", prompt: "Basquiat, Keith Haring type painting" },
    { name: "Y2k", year: "2000-2006", prompt: "Y2K aesthetic, 8-bit aesthetic, colorful" },
    { name: "NFT Art", year: "2017-2022", prompt: "Bored Apes, Cryptopunk NFTs" },
    { name: "Refik Anadol", year: "2019-Present", prompt: "Refik Anadol AI art" },
    { name: "Future", year: "Present-?", prompt: "abstract art of the future" }
];
